import {
  Property,
  LandlordApplication,
  Inquiry,
  ActivityLog,
  ModerationLog,
  RentalApplication,
  LeaseAgreement,
  RentPaymentRecord,
  InspectionChecklist,
  PropertyInspectionBooking,
} from '../types';

export const INITIAL_INSPECTION_BOOKINGS: PropertyInspectionBooking[] = [
  {
    id: 'insp_bk_001',
    userId: 'usr_tenant_001',
    propertyId: 'prop_001',
    type: 'in_person',
    scheduledAt: new Date(Date.now() + 86400000).toISOString(),
    price: 15000,
    paymentStatus: 'confirmed',
    status: 'confirmed',
    addressRevealed: true,
    revealExpiresAt: new Date(Date.now() + 86400000 + 24 * 3600000).toISOString(),
    createdAt: new Date().toISOString(),
  }
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop_001',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    landlordEmail: 'grace.nakimera@property.ug',
    landlordVerified: true,
    createdBy: 'usr_landlord_001',
    title: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    description:
      'Executive contemporary apartment situated in the serene diplomatic heart of Kololo. Features an open-concept living area, panoramic balcony overlooking the green Kololo ridge, master bedroom en-suite with walk-in closet, automated solar-inverter backup, and 24/7 armed security guard post. Fully fitted kitchen with granite countertops and Bosch induction stove.',
    propertyType: 'apartment',
    rentAmount: 2800000,
    currency: 'UGX',
    securityDeposit: 2800000,
    availableDate: '2026-10-01',
    address: 'Plot 14, Prince Charles Drive',
    city: 'Kampala',
    neighborhood: 'Kololo',
    stateRegion: 'Central',
    exactLatitude: 0.3341,
    exactLongitude: 32.5962,
    neighborhoodLatitude: 0.3310,
    neighborhoodLongitude: 32.5930,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1250,
    floorNumber: 3,
    parkingSpaces: 2,
    furnished: 'yes',
    amenities: [
      'High-speed Fiber WiFi',
      'Standby Generator & Solar Inverter',
      '24/7 Security & CCTV',
      'NWSC Water + 10,000L Reserve Tank',
      'Swimming Pool',
      'Gym & Fitness Studio',
      'Balcony with Ridge View',
      'Dedicated Paved Parking',
      'Air Conditioning',
    ],
    images: [
      {
        id: 'img_001_1',
        propertyId: 'prop_001',
        url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&auto=format&fit=crop&q=80',
        isMain: true,
        sortOrder: 1,
        status: 'approved',
        createdAt: '2026-03-01T10:00:00Z',
        resolution: '1920x1080',
        fileSize: '2.4 MB',
      },
      {
        id: 'img_001_2',
        propertyId: 'prop_001',
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 2,
        status: 'approved',
        createdAt: '2026-03-01T10:05:00Z',
        resolution: '1920x1280',
        fileSize: '1.9 MB',
      },
      {
        id: 'img_001_3',
        propertyId: 'prop_001',
        url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 3,
        status: 'approved',
        createdAt: '2026-03-01T10:10:00Z',
        resolution: '2048x1365',
        fileSize: '3.1 MB',
      },
      {
        id: 'img_001_4',
        propertyId: 'prop_001',
        url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 4,
        status: 'approved',
        createdAt: '2026-03-01T10:12:00Z',
        resolution: '1800x1200',
        fileSize: '1.7 MB',
      },
      {
        id: 'img_001_5',
        propertyId: 'prop_001',
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 5,
        status: 'approved',
        createdAt: '2026-03-01T10:15:00Z',
        resolution: '1920x1080',
        fileSize: '2.1 MB',
      },
    ],
    status: 'published',
    isFeatured: true,
    publishedAt: '2026-03-02T14:00:00Z',
    createdAt: '2026-03-01T09:45:00Z',
    updatedAt: '2026-03-02T14:00:00Z',
    viewsCount: 342,
    favoritesCount: 28,
    inquiriesCount: 6,
    driveDocumentName: 'SafeNest_Lease_Agreement_PrinceCharles.pdf',
    driveDocumentLink: 'https://drive.google.com',
  },
  {
    id: 'prop_002',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    landlordEmail: 'grace.nakimera@property.ug',
    landlordVerified: true,
    createdBy: 'usr_landlord_001',
    title: 'Spacious 4-Bedroom Family Villa with Private Garden',
    description:
      'Serene residential villa in premier Naguru hill summit. Boasts expansive landscaped garden with palm trees, master suite with jacuzzi and balcony, self-contained staff quarters (DSQ), perimeter electric fence, double covered garage, and dual water storage tanks with solar water heating.',
    propertyType: 'villa',
    rentAmount: 5200000,
    currency: 'UGX',
    securityDeposit: 5200000,
    availableDate: '2026-10-15',
    address: 'Plot 8B, Naguru Summit View Road',
    city: 'Kampala',
    neighborhood: 'Naguru',
    stateRegion: 'Central',
    exactLatitude: 0.3475,
    exactLongitude: 32.6102,
    neighborhoodLatitude: 0.3450,
    neighborhoodLongitude: 32.6120,
    bedrooms: 4,
    bathrooms: 3.5,
    squareFeet: 3100,
    floorNumber: 1,
    parkingSpaces: 4,
    furnished: 'partial',
    amenities: [
      'Landscaped Garden',
      'Standby Generator & Solar Inverter',
      '24/7 Security & CCTV',
      'Staff Quarters (DSQ)',
      'Electric Perimeter Fence',
      'Perimeter Floodlights',
      'Pet Friendly',
      'Dedicated Paved Parking',
      'Solar Water Heating',
    ],
    images: [
      {
        id: 'img_002_1',
        propertyId: 'prop_002',
        url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&auto=format&fit=crop&q=80',
        isMain: true,
        sortOrder: 1,
        status: 'approved',
        createdAt: '2026-03-03T11:00:00Z',
        resolution: '2048x1365',
        fileSize: '3.4 MB',
      },
      {
        id: 'img_002_2',
        propertyId: 'prop_002',
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 2,
        status: 'approved',
        createdAt: '2026-03-03T11:05:00Z',
        resolution: '1920x1080',
        fileSize: '2.2 MB',
      },
      {
        id: 'img_002_3',
        propertyId: 'prop_002',
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 3,
        status: 'approved',
        createdAt: '2026-03-03T11:10:00Z',
        resolution: '1920x1280',
        fileSize: '2.5 MB',
      },
    ],
    status: 'published',
    isFeatured: true,
    publishedAt: '2026-03-04T09:00:00Z',
    createdAt: '2026-03-03T10:30:00Z',
    updatedAt: '2026-03-04T09:00:00Z',
    viewsCount: 489,
    favoritesCount: 39,
    inquiriesCount: 9,
  },
  {
    id: 'prop_003',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    landlordEmail: 'grace.nakimera@property.ug',
    landlordVerified: true,
    createdBy: 'usr_landlord_001',
    title: 'Chic 1-Bedroom Studio near Ntinda Kyambogo Ring Road',
    description:
      'Ideal for young working professionals or corporate consultants. Located within 3 minutes of Capital Shoppers Ntinda. Gated community with paved access roads, constant NWSC water supply with automatic pressure pump, prepaid Yaka electricity meter, and secure parking.',
    propertyType: 'apartment',
    rentAmount: 1200000,
    currency: 'UGX',
    securityDeposit: 1200000,
    availableDate: '2026-09-20',
    address: 'Semawata Road, Ntinda',
    city: 'Kampala',
    neighborhood: 'Ntinda',
    stateRegion: 'Central',
    exactLatitude: 0.3541,
    exactLongitude: 32.6133,
    neighborhoodLatitude: 0.3510,
    neighborhoodLongitude: 32.6100,
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 620,
    floorNumber: 2,
    parkingSpaces: 1,
    furnished: 'no',
    amenities: [
      'High-speed Fiber WiFi',
      '24/7 Security & CCTV',
      'NWSC Water + 10,000L Reserve Tank',
      'Balcony with Ridge View',
      'Dedicated Paved Parking',
      'Garbage Collection Included',
    ],
    images: [
      {
        id: 'img_003_1',
        propertyId: 'prop_003',
        url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&auto=format&fit=crop&q=80',
        isMain: true,
        sortOrder: 1,
        status: 'approved',
        createdAt: '2026-03-05T14:00:00Z',
        resolution: '1920x1080',
        fileSize: '1.8 MB',
      },
      {
        id: 'img_003_2',
        propertyId: 'prop_003',
        url: 'https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 2,
        status: 'approved',
        createdAt: '2026-03-05T14:05:00Z',
        resolution: '1920x1200',
        fileSize: '1.6 MB',
      },
    ],
    status: 'published',
    isFeatured: false,
    publishedAt: '2026-03-06T10:00:00Z',
    createdAt: '2026-03-05T13:40:00Z',
    updatedAt: '2026-03-06T10:00:00Z',
    viewsCount: 275,
    favoritesCount: 19,
    inquiriesCount: 4,
  },
  {
    id: 'prop_004',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    landlordEmail: 'grace.nakimera@property.ug',
    landlordVerified: true,
    createdBy: 'usr_landlord_001',
    title: 'Lake Breeze 3-Bedroom Lakeview Residence in Entebbe',
    description:
      'Breathtaking home located 5 minutes from Lake Victoria shore and Entebbe Golf Club. Cool tropical cross-breeze, expansive glass patio, modern granite kitchen, master jacuzzi, landscaped front lawn, solar power system, and round-the-clock guards.',
    propertyType: 'house',
    rentAmount: 3800000,
    currency: 'UGX',
    securityDeposit: 3800000,
    availableDate: '2026-10-01',
    address: 'Manyago Crescent, Entebbe Municipality',
    city: 'Entebbe',
    neighborhood: 'Manyago',
    stateRegion: 'Central',
    exactLatitude: 0.0512,
    exactLongitude: 32.4637,
    neighborhoodLatitude: 0.0490,
    neighborhoodLongitude: 32.4610,
    bedrooms: 3,
    bathrooms: 2.5,
    squareFeet: 2100,
    floorNumber: 1,
    parkingSpaces: 3,
    furnished: 'partial',
    amenities: [
      'High-speed Fiber WiFi',
      'Standby Generator & Solar Inverter',
      '24/7 Security & CCTV',
      'Landscaped Garden',
      'Solar Water Heating',
      'Lake Victoria Horizon View',
      'Dedicated Paved Parking',
    ],
    images: [
      {
        id: 'img_004_1',
        propertyId: 'prop_004',
        url: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=1200&auto=format&fit=crop&q=80',
        isMain: true,
        sortOrder: 1,
        status: 'approved',
        createdAt: '2026-03-07T08:00:00Z',
        resolution: '2048x1365',
        fileSize: '2.9 MB',
      },
      {
        id: 'img_004_2',
        propertyId: 'prop_004',
        url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 2,
        status: 'approved',
        createdAt: '2026-03-07T08:10:00Z',
        resolution: '1920x1080',
        fileSize: '2.4 MB',
      },
    ],
    status: 'published',
    isFeatured: true,
    publishedAt: '2026-03-07T12:00:00Z',
    createdAt: '2026-03-07T07:30:00Z',
    updatedAt: '2026-03-07T12:00:00Z',
    viewsCount: 290,
    favoritesCount: 22,
    inquiriesCount: 5,
  },
  // Property with photos awaiting Admin Moderation (Demonstrates Module 5 & Module 6)
  {
    id: 'prop_005',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    landlordEmail: 'grace.nakimera@property.ug',
    landlordVerified: true,
    createdBy: 'usr_landlord_001',
    title: 'Brand New Bugolobi Village View 2-Bed Flat',
    description:
      'Newly finished block in Bugolobi, 2 minutes from Village Mall and Spring Road. Modern Italian floor tiles, private balcony, silent elevator, standby backup Cummins generator, and borehole water backup.',
    propertyType: 'apartment',
    rentAmount: 2200000,
    currency: 'UGX',
    securityDeposit: 2200000,
    availableDate: '2026-10-01',
    address: 'Luthuli Avenue, Bugolobi',
    city: 'Kampala',
    neighborhood: 'Bugolobi',
    stateRegion: 'Central',
    exactLatitude: 0.3129,
    exactLongitude: 32.6184,
    neighborhoodLatitude: 0.3100,
    neighborhoodLongitude: 32.6150,
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1100,
    floorNumber: 4,
    parkingSpaces: 1,
    furnished: 'no',
    amenities: [
      'Standby Generator & Solar Inverter',
      '24/7 Security & CCTV',
      'NWSC Water + 10,000L Reserve Tank',
      'Balcony with Ridge View',
      'Elevator Access',
      'Dedicated Paved Parking',
    ],
    images: [
      {
        id: 'img_005_1',
        propertyId: 'prop_005',
        url: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&auto=format&fit=crop&q=80',
        isMain: true,
        sortOrder: 1,
        status: 'pending',
        createdAt: '2026-03-12T11:00:00Z',
        resolution: '1920x1080',
        fileSize: '2.1 MB',
      },
      {
        id: 'img_005_2',
        propertyId: 'prop_005',
        url: 'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 2,
        status: 'pending',
        createdAt: '2026-03-12T11:05:00Z',
        resolution: '1920x1200',
        fileSize: '1.9 MB',
      },
      {
        id: 'img_005_3',
        propertyId: 'prop_005',
        url: 'https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 3,
        status: 'pending',
        createdAt: '2026-03-12T11:10:00Z',
        resolution: '1800x1200',
        fileSize: '1.8 MB',
      },
    ],
    status: 'pending',
    isFeatured: false,
    createdAt: '2026-03-12T10:45:00Z',
    updatedAt: '2026-03-12T11:15:00Z',
    viewsCount: 42,
    favoritesCount: 3,
    inquiriesCount: 0,
  },
  // Property with a rejected photo (Demonstrates Re-upload flow)
  {
    id: 'prop_006',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    landlordEmail: 'grace.nakimera@property.ug',
    landlordVerified: true,
    createdBy: 'usr_landlord_001',
    title: 'Modern 3-Bedroom Penthouse in Nakasero Hill',
    description:
      'Ultra-exclusive penthouse in Nakasero residential enclave. Private rooftop deck with views of Kampala central business skyline, smart home lighting, and private elevator landing.',
    propertyType: 'apartment',
    rentAmount: 6500000,
    currency: 'UGX',
    securityDeposit: 6500000,
    availableDate: '2026-11-01',
    address: 'Plot 31, Akii-Bua Road, Nakasero',
    city: 'Kampala',
    neighborhood: 'Nakasero',
    stateRegion: 'Central',
    exactLatitude: 0.3275,
    exactLongitude: 32.5815,
    neighborhoodLatitude: 0.3250,
    neighborhoodLongitude: 32.5800,
    bedrooms: 3,
    bathrooms: 3,
    squareFeet: 2400,
    floorNumber: 6,
    parkingSpaces: 2,
    furnished: 'yes',
    amenities: [
      'High-speed Fiber WiFi',
      'Standby Generator & Solar Inverter',
      '24/7 Security & CCTV',
      'Rooftop Terrace & BBQ Area',
      'Swimming Pool',
      'Gym & Fitness Studio',
      'Elevator Access',
      'Air Conditioning',
    ],
    images: [
      {
        id: 'img_006_1',
        propertyId: 'prop_006',
        url: 'https://images.unsplash.com/photo-1502005229762-ee1b2da97ba4?w=1200&auto=format&fit=crop&q=80',
        isMain: true,
        sortOrder: 1,
        status: 'approved',
        createdAt: '2026-03-10T09:00:00Z',
        resolution: '1920x1080',
        fileSize: '2.5 MB',
      },
      {
        id: 'img_006_2',
        propertyId: 'prop_006',
        url: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=1200&auto=format&fit=crop&q=80',
        isMain: false,
        sortOrder: 2,
        status: 'rejected',
        rejectionReason: 'Blurry/Low quality',
        moderationNotes: 'Photo resolution is grainy and lighting is too dark. Please re-upload daytime shot of the kitchen.',
        reviewedBy: 'David Kato (Admin)',
        reviewedAt: '2026-03-11T14:30:00Z',
        createdAt: '2026-03-10T09:05:00Z',
        resolution: '800x600',
        fileSize: '410 KB',
      },
    ],
    status: 'pending_photos',
    isFeatured: false,
    moderationNotes: '1 photo rejected due to poor lighting. Re-upload required before publishing.',
    createdAt: '2026-03-10T08:50:00Z',
    updatedAt: '2026-03-11T14:30:00Z',
    viewsCount: 65,
    favoritesCount: 7,
    inquiriesCount: 1,
  },
];

export const INITIAL_APPLICATIONS: LandlordApplication[] = [
  {
    id: 'app_001',
    userId: 'usr_applicant_001',
    fullName: 'Sarah Namubiru',
    email: 'sarah.namubiru@estate.co.ug',
    phone: '+256 788 123 990',
    nationalIdNumber: 'CF9104439201EBB',
    physicalAddress: 'Plot 12, Manyago Road, Entebbe Municipality',
    businessName: 'Namubiru Heritage Properties',
    businessRegistrationNumber: 'BRN-882941-KLA',
    tinNumber: '1004928190',
    yearsExperience: 6,
    propertyCount: 4,
    propertyLocations: 'Entebbe (2 units), Muyenga (1 villa), Jinja (1 commercial block)',
    documents: {
      idCardUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
      ownershipDocumentUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
      tinCertificateUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=800&auto=format&fit=crop&q=80',
    },
    referenceName: 'Eng. Patrick Lwanga',
    referencePhone: '+256 702 991 334',
    status: 'under_review',
    adminNotes: 'National ID and URA TIN verified against Uganda company registry. Awaiting final site title inspection.',
    createdAt: '2026-03-12T09:30:00Z',
    updatedAt: '2026-03-12T14:00:00Z',
  },
  {
    id: 'app_002',
    userId: 'usr_applicant_002',
    fullName: 'Moses Byaruhanga',
    email: 'm.byaruhanga@gmail.com',
    phone: '+256 701 556 221',
    nationalIdNumber: 'CM7901192834KLA',
    physicalAddress: 'Bukoto-Kisuule Road, Kampala',
    businessName: 'Byaruhanga Rentals',
    tinNumber: '1019283741',
    yearsExperience: 3,
    propertyCount: 2,
    propertyLocations: 'Bukoto, Kiwatule',
    documents: {
      idCardUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
      ownershipDocumentUrl: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&auto=format&fit=crop&q=80',
    },
    referenceName: 'Agnes Tumusiime',
    referencePhone: '+256 772 100 445',
    status: 'submitted',
    createdAt: '2026-03-13T06:20:00Z',
    updatedAt: '2026-03-13T06:20:00Z',
  },
];

export const INITIAL_INQUIRIES: Inquiry[] = [
  {
    id: 'inq_sarah',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    propertyImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80',
    userId: 'usr_sarah_k',
    landlordId: 'usr_landlord_001',
    name: 'Sarah K.',
    email: 'sarah.k@gmail.com',
    phone: '+256 701 332 991',
    moveInDate: '2026-10-01',
    message: 'Is this available? I would like to schedule a walk-through this week.',
    preferredContact: 'whatsapp',
    status: 'new',
    createdAt: '2026-03-13T07:15:00Z',
  },
  {
    id: 'inq_mike',
    propertyId: 'prop_003',
    propertyTitle: 'Chic 1-Bedroom Studio near Ntinda Kyambogo Ring Road',
    propertyImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&auto=format&fit=crop&q=80',
    userId: 'usr_mike_r',
    landlordId: 'usr_landlord_001',
    name: 'Mike R.',
    email: 'mike.r@gmail.com',
    phone: '+256 772 884 102',
    moveInDate: '2026-09-25',
    message: 'Can I view Saturday? Looking to move in by end of month.',
    preferredContact: 'in_app',
    status: 'new',
    createdAt: '2026-03-13T05:40:00Z',
  },
  {
    id: 'inq_001',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    propertyImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&auto=format&fit=crop&q=80',
    userId: 'usr_tenant_001',
    landlordId: 'usr_landlord_001',
    name: 'Brian Mukasa',
    email: 'brian.mukasa@gmail.com',
    phone: '+256 755 889 004',
    moveInDate: '2026-10-01',
    message:
      'Hello Grace, I work at an international fintech in Nakasero and looking for a quiet 2-bed in Kololo. Is the standby generator automatic during power cuts? Can I schedule a physical inspection this Saturday at 11 AM?',
    preferredContact: 'whatsapp',
    status: 'new',
    createdAt: '2026-03-12T16:20:00Z',
  },
  {
    id: 'inq_002',
    propertyId: 'prop_002',
    propertyTitle: 'Spacious 4-Bedroom Family Villa with Private Garden',
    propertyImage: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&auto=format&fit=crop&q=80',
    userId: 'usr_tenant_002',
    landlordId: 'usr_landlord_001',
    name: 'Dr. Timothy Okello',
    email: 't.okello@who.int',
    phone: '+256 774 200 918',
    moveInDate: '2026-10-15',
    message:
      'Greetings, we are relocating our family from Nairobi to Naguru. Does the villa allow small family pets? Also, are water filtration systems installed on the overhead tank?',
    preferredContact: 'phone',
    status: 'viewing_scheduled',
    createdAt: '2026-03-11T10:15:00Z',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'log_001',
    userId: 'usr_admin_001',
    userName: 'David Kato',
    action: 'Approved Property Listing',
    entityType: 'property',
    entityId: 'prop_001',
    details: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View was approved and published.',
    createdAt: '2026-03-02T14:00:00Z',
  },
  {
    id: 'log_002',
    userId: 'usr_admin_001',
    userName: 'David Kato',
    action: 'Rejected Photo (Blurry)',
    entityType: 'photo',
    entityId: 'img_006_2',
    details: 'Rejected photo img_006_2 on Nakasero Penthouse: Blurry/Low quality lighting.',
    createdAt: '2026-03-11T14:30:00Z',
  },
  {
    id: 'log_003',
    userId: 'usr_landlord_001',
    userName: 'Grace Nakimera',
    action: 'Submitted New Property',
    entityType: 'property',
    entityId: 'prop_005',
    details: 'Submitted "Brand New Bugolobi Village View 2-Bed Flat" with 3 photos for admin moderation.',
    createdAt: '2026-03-12T11:15:00Z',
  },
  {
    id: 'log_004',
    userId: 'usr_applicant_001',
    userName: 'Sarah Namubiru',
    action: 'Submitted Landlord Application',
    entityType: 'application',
    entityId: 'app_001',
    details: 'Submitted landlord verification documents including NIN and URA TIN.',
    createdAt: '2026-03-12T09:30:00Z',
  },
];

export const INITIAL_MODERATION_LOGS: ModerationLog[] = [
  {
    id: 'mod_001',
    propertyId: 'prop_006',
    propertyTitle: 'Modern 3-Bedroom Penthouse in Nakasero Hill',
    imageId: 'img_006_2',
    moderatorId: 'usr_admin_001',
    moderatorName: 'David Kato',
    action: 'reject',
    reason: 'Blurry/Low quality',
    notes: 'Photo resolution is grainy and lighting is too dark. Please re-upload daytime shot of the kitchen.',
    createdAt: '2026-03-11T14:30:00Z',
  },
  {
    id: 'mod_002',
    propertyId: 'prop_006',
    propertyTitle: 'Modern 3-Bedroom Penthouse in Nakasero Hill',
    imageId: 'img_006_1',
    moderatorId: 'usr_admin_001',
    moderatorName: 'David Kato',
    action: 'approve',
    createdAt: '2026-03-11T14:28:00Z',
  },
];

// ====================================================
// PHASE 2: INITIAL RENTAL APPLICATIONS (TENANT DOSSIERS)
// ====================================================
export const INITIAL_RENTAL_APPLICATIONS: RentalApplication[] = [
  {
    id: 'rent_app_001',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    propertyImage: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    propertyAddress: 'Plot 14, Prince Charles Drive',
    propertyCity: 'Kampala',
    rentAmount: 2800000,
    tenantId: 'usr_user_001',
    tenantName: 'Brian Mukasa',
    tenantEmail: 'brian.mukasa@techug.io',
    tenantPhone: '+256 701 445 667',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    status: 'approved',
    personalInfo: {
      fullName: 'Brian Mukasa',
      email: 'brian.mukasa@techug.io',
      phone: '+256 701 445 667',
      dob: '1992-06-18',
      nationalIdNumber: 'CM92014728X4KA',
      currentAddress: 'Apartment 4B, Bukoto Heights, Kampala',
      maritalStatus: 'Single',
      nextOfKinName: 'Dorothy Namukasa',
      nextOfKinPhone: '+256 772 889 001',
    },
    employmentInfo: {
      employmentStatus: 'employed',
      employerName: 'MTN Uganda Ltd (HQ Nyonyi Gardens)',
      jobTitle: 'Senior Cloud Solutions Architect',
      monthlyIncome: 8500000,
      durationYears: 4,
      officeAddress: 'Plot 69-71 Jinja Road, Kampala',
    },
    rentalHistory: {
      previousLandlordName: 'Eng. Patrick Kigozi',
      previousLandlordPhone: '+256 772 109 283',
      previousAddress: 'Bukoto Heights Apartments, Kampala',
      reasonForMoving: 'Relocating closer to workplace and quiet residential environment',
      lengthOfStayMonths: 24,
    },
    references: [
      {
        name: 'Dr. Arthur Ssekandi',
        phone: '+256 782 554 112',
        relationship: 'Professional Mentor',
        organization: 'Makerere University CoCIS',
      },
      {
        name: 'Clare Babirye',
        phone: '+256 704 991 223',
        relationship: 'Colleague / Lead Engineer',
        organization: 'MTN Uganda',
      },
    ],
    preferences: {
      moveInDate: '2026-10-01',
      leaseDurationMonths: 12,
      occupantsCount: 1,
      hasPets: false,
      vehicleCount: 1,
    },
    documents: [
      {
        id: 'doc_nin_01',
        name: 'Uganda_NIN_BrianMukasa_FrontBack.pdf',
        type: 'national_id',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
        uploadedAt: '2026-09-01T10:00:00Z',
      },
      {
        id: 'doc_pay_01',
        name: 'MTN_Uganda_Payslips_Q2_2026.pdf',
        type: 'payslip',
        url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600',
        uploadedAt: '2026-09-01T10:05:00Z',
      },
      {
        id: 'doc_rec_01',
        name: 'Recommendation_PatrickKigozi_FormerLandlord.pdf',
        type: 'recommendation_letter',
        url: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600',
        uploadedAt: '2026-09-01T10:08:00Z',
      },
    ],
    adminNotes: 'Strong financial profile, verified employment at MTN Uganda HQ. Recommended for lease execution.',
    reviewedBy: 'Grace Nakimera',
    reviewedAt: '2026-09-03T11:20:00Z',
    createdAt: '2026-09-01T10:10:00Z',
    updatedAt: '2026-09-03T11:20:00Z',
  },
  {
    id: 'rent_app_002',
    propertyId: 'prop_002',
    propertyTitle: 'Spacious 3-Bedroom Naguru Hilltop Villa with Garden',
    propertyImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    propertyAddress: 'Naguru Drive, Plot 88',
    propertyCity: 'Kampala',
    rentAmount: 4500000,
    tenantId: 'usr_user_002',
    tenantName: 'Fiona Atuhaire',
    tenantEmail: 'fiona.atuhaire@pwc.com',
    tenantPhone: '+256 782 119 443',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    status: 'under_review',
    personalInfo: {
      fullName: 'Fiona Atuhaire',
      email: 'fiona.atuhaire@pwc.com',
      phone: '+256 782 119 443',
      dob: '1989-11-24',
      nationalIdNumber: 'CF89041289Z1LA',
      currentAddress: 'Plot 12 Kira Road, Kamwokya, Kampala',
      maritalStatus: 'Married',
      nextOfKinName: 'Ronald Atuhaire',
      nextOfKinPhone: '+256 772 334 990',
    },
    employmentInfo: {
      employmentStatus: 'employed',
      employerName: 'PricewaterhouseCoopers (PwC Uganda)',
      jobTitle: 'Senior Assurance Manager',
      monthlyIncome: 12000000,
      durationYears: 6,
      officeAddress: 'Communications House, Colville Street, Kampala',
    },
    rentalHistory: {
      previousLandlordName: 'Hajji Sulaiman Kibirige',
      previousLandlordPhone: '+256 752 990 114',
      previousAddress: 'Kamwokya Residential Block 3',
      reasonForMoving: 'Expanding family; seeking dedicated garden and perimeter security',
      lengthOfStayMonths: 36,
    },
    references: [
      {
        name: 'Partner Richard Tumusiime',
        phone: '+256 701 334 000',
        relationship: 'Audit Partner / Supervisor',
        organization: 'PwC Uganda',
      },
    ],
    preferences: {
      moveInDate: '2026-10-15',
      leaseDurationMonths: 12,
      occupantsCount: 3,
      hasPets: true,
      petDetails: '1 trained Golden Retriever (vaccinated)',
      vehicleCount: 2,
    },
    documents: [
      {
        id: 'doc_nin_02',
        name: 'NationalID_FionaAtuhaire.pdf',
        type: 'national_id',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
        uploadedAt: '2026-09-08T14:15:00Z',
      },
      {
        id: 'doc_pay_02',
        name: 'PwC_Salary_Slip_August2026.pdf',
        type: 'payslip',
        url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=600',
        uploadedAt: '2026-09-08T14:18:00Z',
      },
    ],
    adminNotes: 'Application received. Pending landlord physical site walkthrough confirmation.',
    reviewedBy: 'Grace Nakimera',
    reviewedAt: '2026-09-09T08:30:00Z',
    createdAt: '2026-09-08T14:20:00Z',
    updatedAt: '2026-09-09T08:30:00Z',
  },
  {
    id: 'rent_app_003',
    propertyId: 'prop_004',
    propertyTitle: 'Contemporary 2-Bed Furnished Flat in Ntinda Minister’s Village',
    propertyImage: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    propertyAddress: 'Minister’s Village, Ntinda Close',
    propertyCity: 'Kampala',
    rentAmount: 1600000,
    tenantId: 'usr_user_003',
    tenantName: 'Joseph Ochieng',
    tenantEmail: 'joseph.ochieng@stanbic.co.ug',
    tenantPhone: '+256 752 884 192',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    status: 'submitted',
    personalInfo: {
      fullName: 'Joseph Ochieng',
      email: 'joseph.ochieng@stanbic.co.ug',
      phone: '+256 752 884 192',
      dob: '1995-03-12',
      nationalIdNumber: 'CM95028471K2OT',
      currentAddress: 'Kyambogo Road, Nakawa, Kampala',
      maritalStatus: 'Single',
      nextOfKinName: 'Moses Ochieng',
      nextOfKinPhone: '+256 772 443 112',
    },
    employmentInfo: {
      employmentStatus: 'employed',
      employerName: 'Stanbic Bank Uganda (Crested Towers Branch)',
      jobTitle: 'Treasury Operations Analyst',
      monthlyIncome: 4800000,
      durationYears: 3,
      officeAddress: 'Crested Towers, Short Tower, 17 Hannington Road',
    },
    rentalHistory: {
      previousLandlordName: 'Christine Alupo',
      previousLandlordPhone: '+256 701 992 110',
      previousAddress: 'Nakawa Housing Estate',
      reasonForMoving: 'Looking for a furnished apartment with standby backup power',
      lengthOfStayMonths: 18,
    },
    references: [
      {
        name: 'Brenda Namagembe',
        phone: '+256 772 665 009',
        relationship: 'Department Head',
        organization: 'Stanbic Bank Uganda',
      },
    ],
    preferences: {
      moveInDate: '2026-10-01',
      leaseDurationMonths: 6,
      occupantsCount: 1,
      hasPets: false,
      vehicleCount: 1,
    },
    documents: [
      {
        id: 'doc_nin_03',
        name: 'Uganda_NIN_JosephOchieng.pdf',
        type: 'national_id',
        url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600',
        uploadedAt: '2026-09-12T09:10:00Z',
      },
    ],
    createdAt: '2026-09-12T09:15:00Z',
    updatedAt: '2026-09-12T09:15:00Z',
  },
];

// ====================================================
// PHASE 2: INITIAL LEASE AGREEMENTS (DIGITAL LEASES)
// ====================================================
export const INITIAL_LEASES: LeaseAgreement[] = [
  {
    id: 'lease_001',
    applicationId: 'rent_app_001',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    propertyAddress: 'Plot 14, Prince Charles Drive',
    propertyCity: 'Kampala',
    tenantId: 'usr_user_001',
    tenantName: 'Brian Mukasa',
    tenantEmail: 'brian.mukasa@techug.io',
    tenantPhone: '+256 701 445 667',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    startDate: '2026-09-01',
    endDate: '2027-08-31',
    durationMonths: 12,
    monthlyRent: 2800000,
    securityDeposit: 2800000,
    paymentDueDate: 1, // 1st of every month
    lateFeeAmount: 100000,
    noticePeriodDays: 60,
    terms: {
      petPolicy: 'Pets permitted only upon prior written consent from landlord. No commercial breeding.',
      guestPolicy: 'Guests staying longer than 14 consecutive days must be reported to property security.',
      maintenanceResponsibilities: 'Landlord maintains structural fittings, roof, exterior paint, solar-inverter and bore water pump. Tenant maintains internal light fixtures, bulbs, and normal interior cleanliness.',
      utilityResponsibilities: 'Tenant is directly responsible for NWSC Water metered consumption and UMEME Yaka electricity prepaid token replenishment.',
      quietHours: 'Strict quiet hours between 10:00 PM and 6:00 AM on weekdays; 11:00 PM and 7:00 AM on weekends.',
      sublettingPolicy: 'Subletting, Airbnb hosting, or unapproved third-party assignments are strictly prohibited under penalty of immediate eviction.',
      specialClauses: 'Automatic lease renewal option provided tenant issues 60 days advance written notice before expiration.',
    },
    landlordSignature: {
      signedByName: 'Grace Nakimera',
      signatureData: 'Grace Nakimera [SEALED: SN-LD-KLA-2026-881]',
      signedAt: '2026-09-03T14:30:00Z',
    },
    tenantSignature: {
      signedByName: 'Brian Mukasa',
      signatureData: 'Brian Mukasa [DIGITALLY SIGNED: NIN CM92014728X4KA]',
      signedAt: '2026-09-03T16:15:00Z',
    },
    status: 'active',
    driveDocumentId: 'drive_lease_001',
    driveDocumentLink: 'https://drive.google.com',
    createdAt: '2026-09-03T14:00:00Z',
    updatedAt: '2026-09-03T16:15:00Z',
  },
  {
    id: 'lease_002',
    propertyId: 'prop_006',
    propertyTitle: 'Modern 3-Bedroom Penthouse in Nakasero Hill',
    propertyAddress: 'Kyaggwe Road, Nakasero',
    propertyCity: 'Kampala',
    tenantId: 'usr_user_002',
    tenantName: 'Fiona Atuhaire',
    tenantEmail: 'fiona.atuhaire@pwc.com',
    tenantPhone: '+256 782 119 443',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    landlordPhone: '+256 772 334 112',
    startDate: '2026-10-01',
    endDate: '2027-09-30',
    durationMonths: 12,
    monthlyRent: 4000000,
    securityDeposit: 4000000,
    paymentDueDate: 5,
    lateFeeAmount: 150000,
    noticePeriodDays: 60,
    terms: {
      petPolicy: 'Domestic dog allowed with obedience training certificate.',
      guestPolicy: 'Standard residential guest policy. Commercial gatherings require management authorization.',
      maintenanceResponsibilities: 'Landlord maintains elevator service, generator diesel fuel, and security perimeter.',
      utilityResponsibilities: 'Tenant covers Yaka electricity units and flat NWSC sanitation fee of UGX 50,000/mo.',
      quietHours: '10:00 PM to 7:00 AM daily.',
      sublettingPolicy: 'Subletting prohibited.',
    },
    landlordSignature: {
      signedByName: 'Grace Nakimera',
      signatureData: 'Grace Nakimera [SEALED: SN-LD-KLA-2026-881]',
      signedAt: '2026-09-10T11:00:00Z',
    },
    status: 'pending_signature',
    createdAt: '2026-09-10T10:30:00Z',
    updatedAt: '2026-09-10T11:00:00Z',
  },
];

// ====================================================
// PHASE 2: MANUAL RENT TRACKING (NO PAYMENT GATEWAY)
// ====================================================
export const INITIAL_RENT_PAYMENTS: RentPaymentRecord[] = [
  {
    id: 'pay_001',
    receiptNumber: 'SN-RCP-2026-0001',
    leaseId: 'lease_001',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    tenantId: 'usr_user_001',
    tenantName: 'Brian Mukasa',
    tenantPhone: '+256 701 445 667',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    amount: 2800000,
    billingPeriod: 'Security Deposit (Refundable)',
    dueDate: '2026-09-01',
    paidDate: '2026-09-01',
    status: 'paid',
    paymentMethod: 'bank_transfer',
    referenceNumber: 'STB-KLA-441092',
    notes: 'Stanbic Bank Uganda direct bank transfer to Landlord Centenary Bank account. Deposit verified.',
    confirmedBy: 'Grace Nakimera (Landlord)',
    confirmedAt: '2026-09-01T15:00:00Z',
    driveReceiptLink: 'https://drive.google.com',
    createdAt: '2026-09-01T12:00:00Z',
  },
  {
    id: 'pay_002',
    receiptNumber: 'SN-RCP-2026-0012',
    leaseId: 'lease_001',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    tenantId: 'usr_user_001',
    tenantName: 'Brian Mukasa',
    tenantPhone: '+256 701 445 667',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    amount: 2800000,
    billingPeriod: 'September 2026 Rent',
    dueDate: '2026-09-01',
    paidDate: '2026-09-02',
    status: 'paid',
    paymentMethod: 'mtn_momo',
    referenceNumber: 'MTN-UG-982147',
    notes: 'Received via MTN Mobile Money merchant transfer. Verified against MTN statement.',
    confirmedBy: 'Grace Nakimera (Landlord)',
    confirmedAt: '2026-09-02T10:14:00Z',
    driveReceiptLink: 'https://drive.google.com',
    createdAt: '2026-09-02T09:40:00Z',
  },
  {
    id: 'pay_003',
    receiptNumber: 'SN-RCP-2026-0028',
    leaseId: 'lease_001',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    tenantId: 'usr_user_001',
    tenantName: 'Brian Mukasa',
    tenantPhone: '+256 701 445 667',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    amount: 2800000,
    billingPeriod: 'October 2026 Rent',
    dueDate: '2026-10-01',
    status: 'pending',
    paymentMethod: 'mtn_momo',
    notes: 'Standard monthly rent payment scheduled.',
    confirmedBy: 'Pending Confirmation',
    createdAt: '2026-09-10T08:00:00Z',
  },
];

// ====================================================
// PHASE 2: MOVE-IN & MOVE-OUT INSPECTION CHECKLISTS
// ====================================================
export const INITIAL_INSPECTIONS: InspectionChecklist[] = [
  {
    id: 'insp_001',
    leaseId: 'lease_001',
    propertyId: 'prop_001',
    propertyTitle: 'Modern 2-Bedroom Luxury Suite with Kololo Hill View',
    tenantId: 'usr_user_001',
    tenantName: 'Brian Mukasa',
    landlordId: 'usr_landlord_001',
    landlordName: 'Grace Nakimera',
    type: 'move_in',
    inspectionDate: '2026-09-02',
    inspectorName: 'Grace Nakimera & Brian Mukasa',
    yakaMeterNumber: '37189920194',
    yakaTokenBalanceUnits: 148.5,
    waterMeterNumber: 'NWSC-KLA-88219',
    waterMeterReadingM3: 1402.6,
    areas: [
      {
        area: 'Living Room & Dining',
        condition: 'excellent',
        notes: 'Walls freshly painted in off-white eggshell. Hardwood parquet polished. Balcony sliding glass door locks smoothly.',
      },
      {
        area: 'Kitchen & Cabinetry',
        condition: 'excellent',
        notes: 'Bosch induction cooktop and oven operational. Granite countertop unblemished. Extractor hood filters clean.',
      },
      {
        area: 'Master Bedroom & En-Suite',
        condition: 'good',
        notes: 'Fitted wardrobes spotless. Water heater boiler fully working with strong water pressure.',
      },
      {
        area: 'Guest Bedroom & Bathroom',
        condition: 'excellent',
        notes: 'All sanitary ware clean and leak-free.',
      },
      {
        area: 'Electricals, Sockets & Inverter',
        condition: 'excellent',
        notes: 'Inverter automatic switch-over tested successfully. All socket outlets live.',
      },
      {
        area: 'Plumbing & Taps',
        condition: 'good',
        notes: 'No drips detected. NWSC main valve accessible in service corridor.',
      },
      {
        area: 'Keys & Access Tokens',
        condition: 'excellent',
        notes: 'Handed over 2 sets of front door deadbolt keys, 2 gate remotes, and 1 security access fob.',
      },
    ],
    landlordSignOff: true,
    landlordSignDate: '2026-09-02T16:00:00Z',
    tenantSignOff: true,
    tenantSignDate: '2026-09-02T16:05:00Z',
    overallStatus: 'completed',
    createdAt: '2026-09-02T15:30:00Z',
  },
];

export const INITIAL_DEALS: import('../types').Deal[] = [
  {
    id: 'deal_001',
    title: 'L-Shaped Velvet Sofa Set',
    category: 'Furniture',
    price: 350000,
    originalPrice: 700000,
    description: 'Used for only 6 months. Selling because I am relocating. Very comfortable and includes 4 throw pillows.',
    photos: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800'],
    city: 'Kampala',
    area: 'Ntinda',
    condition: 'Used - Like New',
    contactPhone: '+256772000000',
    sellerName: 'David Kato',
    durationHours: 48,
    expiresAt: new Date(Date.now() + 86400000 * 1.5).toISOString(),
    viewsCount: 142,
    messagesCount: 12,
    isFeatured: true,
    status: 'active',
    createdBy: 'usr_admin_001',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    isVerifiedSeller: true,
  },
  {
    id: 'deal_002',
    title: 'Hisense 43" Smart TV',
    category: 'Electronics',
    price: 450000,
    originalPrice: 800000,
    description: 'Perfect condition Smart TV. Comes with original remote and wall mount bracket.',
    photos: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800'],
    city: 'Kampala',
    area: 'Bukoto',
    condition: 'Used - Good',
    contactPhone: '+256772000000',
    durationHours: 24,
    expiresAt: new Date(Date.now() + 3600000 * 12).toISOString(),
    viewsCount: 205,
    messagesCount: 8,
    isFeatured: false,
    status: 'active',
    createdBy: 'usr_admin_001',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    isVerifiedSeller: false,
  },
  {
    id: 'deal_003',
    title: 'LG Double Door Fridge',
    category: 'Appliances',
    price: 850000,
    originalPrice: 1200000,
    description: 'Spacious LG fridge. Frost free, energy saving. Minor scratch on the side.',
    photos: ['https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800'],
    city: 'Entebbe',
    area: 'Kitoro',
    condition: 'Used - Good',
    contactPhone: '+256772000000',
    durationHours: 72,
    expiresAt: new Date(Date.now() + 3600000 * 2).toISOString(), // Expiring soon (2 hours)
    viewsCount: 89,
    messagesCount: 3,
    isFeatured: false,
    status: 'active',
    createdBy: 'usr_admin_001',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isVerifiedSeller: true,
  },
  {
    id: 'deal_004',
    title: 'Queen Size Orthopedic Mattress',
    category: 'Home Items',
    price: 200000,
    originalPrice: 450000,
    description: 'High-density orthopedic mattress, very clean, always used with a protector.',
    photos: ['https://images.unsplash.com/photo-1631679706909-1844bbd07221?w=800'],
    city: 'Kampala',
    area: 'Kiwatule',
    condition: 'Used - Good',
    contactPhone: '+256772000000',
    durationHours: 24,
    expiresAt: new Date(Date.now() + 1800000).toISOString(), // Expiring in 30 mins (red)
    viewsCount: 340,
    messagesCount: 22,
    isFeatured: true,
    status: 'active',
    createdBy: 'usr_admin_001',
    createdAt: new Date(Date.now() - 3600000 * 23.5).toISOString(),
    isVerifiedSeller: false,
  },
];

export const INITIAL_DEAL_VIEWS: import('../types').DealViewRecord[] = [];
